export const ActionTypes = {
    LOGINREQUEST : 'request',
    REGISTERREQUEST : 'registerRequest',
    REGISTER : 'register',
    REGISTERREQUESTFAILED : 'registerRequestFiled',
    LOGIN : 'login',
    LOGINREQUESTFAILED : 'loginrequestedfailed',
    USERHOME : 'userhome',
    USERHOMESUCCES : 'userhomesuccess',
    HOME_FAIL : 'userhome',
    ADMINLOGINERQUEST : 'adminloginrequest',
    ADMINLOGINSUCCESS : 'adminregitersuccess',
    ADMINLOGINFAILED : 'adminregiterfailed',
    ADMINHOME: 'adminhome',
    ADMINHOMEREQUEST : 'adminHomeRequest',
    ADMINSELECTDATA : 'adminselectdata',
    ADMINSELECTREQUEST : 'adminselectrequest',
    ADMINUPDATEFAILED :'adminupdatefailed',
    ADMINBLOCKREQUEST : 'admninblock',
    ADMINBLOCKSUCCESS : 'adminblocksuccess',
    ADMINBLOCKFAILED : 'adminblockfailed',
    USERIMAGEUPLOADREQUSET : 'imageuploadrequest',
    USERIMAGEUPLOADSUCCESS : 'imageuploadsuccess',
    USERIMAGEUPLOADFAILED : 'imageuploadfailed',

    USERPROFILEGETREQUEST : 'userprofileget',
    USERPROFILEGETSUCCESS : 'userprofilesuccess',
    USERPROFILEGETFAIL : 'userprofilefailed'

}